spring.application.name=smart-office-management-system
management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.health.show-details=always

#db connection
spring.datasource.url=jdbc:mysql://localhost:3306/smart_office
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
