spring.application.name=smart-office-management-system
management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.health.show-details=always

#db connection
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
